services:
  gateway:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  api:
    image: dggs_explorer_api
    build: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"

  gui:
    image: dggs_explorer_gui
    build: gui
    depends_on:
      - viz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gui.rule=Host(`localhost`)"
      - "traefik.http.services.gui.loadbalancer.server.port=80"
      # redirect localhost to localhost/gui
      - "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^[http://]?localhost[/]?"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=http://gui.localhost"

  viz:
    image: dggs_explorer_viz
    build: viz
    volumes:
      - dggs_data_cubes:/data:ro
    environment:
      DGGS_PROXY_URL: "http://viz.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.viz.rule=Host(`viz.localhost`)"
      - "traefik.http.services.viz.loadbalancer.server.port=80"

volumes:
  dggs_data_cubes:
