services:
  gateway:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  api:
    image: dggs_explorer_api
    build: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/dggs-api`)"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.forceslash=true"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/dggs-api"
      - "traefik.http.services.api.loadbalancer.server.port=80"
  gui:
    image: dggs_explorer_gui
    build: gui
    ports:
      - "9005:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gui.rule=Host(`localhost`) && PathPrefix(`/gui`)"
      - "traefik.http.routers.gui.middlewares=gui-stripprefix"
      - "traefik.http.middlewares.gui-stripprefix.stripprefix.forceslash=true"
      - "traefik.http.middlewares.gui-stripprefix.stripprefix.prefixes=/gui"
      - "traefik.http.services.gui.loadbalancer.server.port=80"
      - "traefik.http.services.gui.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.gui.loadbalancer.sticky.cookie.name=stickysvr"
      - "traefik.http.routers.gui.entrypoints=web"

  viz:
    image: dggs_explorer_viz
    container_name: viz
    build: viz
    environment:
      DGGS_PROXY_URL: "http://localhost/viz"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.viz.rule=Host(`localhost`) && PathPrefix(`/viz`)"
      - "traefik.http.routers.viz.middlewares=viz-stripprefix"
      - "traefik.http.middlewares.viz-stripprefix.stripprefix.forceslash=true"
      - "traefik.http.middlewares.viz-stripprefix.stripprefix.prefixes=/viz"
      - "traefik.http.services.viz.loadbalancer.server.port=80"
